---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70
  eslint:
    enabled: true
  fixme:
    enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules/
- .idea/
