language: node_js
node_js:
  - "6.10.0"

install:
  - npm install

before_deploy:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: spa-front
  acl: public_read
  skip_cleanup: true
  local_dir: public
  region: eu-central-1
  on:
    repo: xvonabur/spa_frontend
    branch: master